baseurl: "/tech"
url: "https://ouaisfieu.github.io"
remote_theme: just-the-docs/just-the-docs

title: "DOCTech"
description: "Petit imprÃ©cis de pseudoscience sociale"
favicon_ico: "/favicon-96x96.png"



aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

aux_links:
  ouaisfi.eu: https://ouaisfieu.github.io/

nav:
  - title: Notions
    url: /notions/



search_enabled: true
color_scheme: light


collections:
  notions:
    output: true
  dossiers:               # â† Ajout de la collection
    output: true          # â† TrÃ¨s important pour gÃ©nÃ©rer les pages HTML
  belgique:                  # â† nom de la collection (tu peux mettre "myspot" si tu prÃ©fÃ¨res)
    output: true             # â† pour gÃ©nÃ©rer les pages HTML
    permalink: /belgique/:path/  # â† structure des URL
    sort_by: title           # â† optionnel, trie par titre
  et-vous:
    output: true
    # permalink: /et-vous/:path/  # â† structure des URL
    
just_the_docs:
  collections:
    notions:
      name: âš™ï¸ MENU
      nav_fold: false
    dossiers:             # â† MÃªme structure pour dossiers
      name: ğŸŸ© Dossiers      # â† Nom affichÃ© dans la navigation
      nav_fold: true     # â† Mettre true si tu veux un repliement dans le menu
    belgique:
      name: ğŸŸ¦ BELGIQUE       # â† titre dans le menu de navigation
      nav_fold: true         # â† false = tout est affichÃ© dans le menu, true = repliÃ©
    et-vous:
      name: ğŸŸ¥ ET QUOI ?
      nav_fold: true


back_to_top: true
back_to_top_text: "â†‘ Haut de page"
